const cartas = [
  {
    cardName: 'Naruto',
    cardDescription: 'Dattebayo',
    cardAttr1: '20',
    cardAttr2: '20',
    cardAttr3: '20',
    cardImage: 'https://olhardigital.com.br/wp-content/uploads/2021/07/Naruto-Classico-e-Naruto-Shippuden-fillers.jpg',
    cardTrunfo: false,
    cardRare: 'normal',
  },
  {
    cardName: 'Sasuke Uchiha',
    cardDescription: 'meu nome é Sasuke Uchiha...',
    cardAttr1: '50',
    cardAttr2: '50',
    cardAttr3: '50',
    cardImage: 'https://criticalhits.com.br/wp-content/uploads/2021/09/sasuke-uchiha-naruto-1200x720-1.jpg',
    cardTrunfo: false,
    cardRare: 'raro',
  },
  {
    cardName: 'Madara Uchiha',
    cardDescription: 'Com ou sem Susano`o',
    cardAttr1: '20',
    cardAttr2: '90',
    cardAttr3: '90',
    cardImage: 'https://avatars.githubusercontent.com/u/1188951?v=4',
    cardTrunfo: false,
    cardRare: 'normal',
  },
  {
    cardName: 'Tobiram Senju',
    cardDescription: 'Uchiha bom é Uchiha ???',
    cardAttr1: '30',
    cardAttr2: '90',
    cardAttr3: '70',
    cardImage: 'https://i.pinimg.com/originals/5a/81/f5/5a81f59e29c52d76d0a1567bf421f36f.png',
    cardRare: 'muito raro',
    cardTrunfo: true,
  },
  {
    cardName: 'Kakashi Hatake',
    cardDescription: 'Jardin dos Amassos',
    cardAttr1: '36',
    cardAttr2: '28',
    cardAttr3: '50',
    cardImage: 'https://img.quizur.com/f/img614da6ac1c2bc2.45012985.jpg?lastEdited=1632478895',
    cardRare: 'raro',
    cardTrunfo: false,
  },
  {
    cardName: 'Jiraiya',
    cardDescription: 'ero sennin',
    cardAttr1: '70',
    cardAttr2: '50',
    cardAttr3: '20',
    cardImage: 'https://pm1.narvii.com/6566/f2acdb36876d7bda318934266dd0c223cf350691_hq.jpg',
    cardRare: 'normal',
    cardTrunfo: false,
  },
  {
    cardName: 'Himawari Uzumaki',
    cardDescription: 'Brincando de esconde-esconde',
    cardAttr1: '70',
    cardAttr2: '50',
    cardAttr3: '20',
    cardImage: 'https://nerdhits.com.br/wp-content/uploads/2021/06/EKJogCeWkAYSyW8.jpg',
    cardRare: 'raro',
    cardTrunfo: false,
  },
  {
    cardName: 'Minato Namikaze',
    cardDescription: 'O Relâmpago Amarelo de Konoha',
    cardAttr1: '70',
    cardAttr2: '70',
    cardAttr3: '10',
    cardImage: 'https://criticalhits.com.br/wp-content/uploads/2021/11/minato-namikaze-naruto-shippuden-quiz.jpg',
    cardRare: 'muito raro',
    cardTrunfo: false,
  },
];

export default cartas;
